[workspace]
members = ["openemc-log", "openemc-pack", "xtask"]
exclude = [
    "defmt-ringbuf",
    "openemc-bootloader",
    "openemc-firmware",
    "openemc-shared",
]
resolver = "2"

[profile.release]
opt-level = 'z'
lto = 'fat'
strip = 'symbols'
