[package]
name = "openemc-build"
description = "OpenEMC build"
authors = ["Sebastian Urban <surban@surban.net>"]
license = "GPL-3.0"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
