[package]
name = "openemc-shared"
description = "OpenEMC shared"
authors = ["Sebastian Urban <surban@surban.net>"]
license = "GPL-3.0"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
defmt = "0.3"
