[build]
target = "thumbv7m-none-eabi"
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Temc-bootloader.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "link-arg=--nmagic",
]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32F103RB"
