name: Driver

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare Linux kernel source
      run: |
        curl https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.19.12.tar.xz | tar xJ
        mv linux-5.19.12 linux
        cp -f .github/workflows/kernel.config linux/.config        
        cd linux
        make modules_prepare -j        
    - name: Build kernel modules
      run: LINUX_DIR=$PWD/linux ./scripts/driver-build.sh -j
    - name: Build devicetree examples
      run: ./scripts/devicetree-build.sh
